name: pttf
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - abseil-cpp=20210324.2
  - absl-py=0.14.1
  - aiofiles=0.7.0
  - aioftp=0.18.1
  - aiohttp=3.7.4.post0
  - alsa-lib=1.2.3
  - appdirs=1.4.4
  - astor=0.8.1
  - astropy=4.3.1
  - astropy-healpix=0.6
  - astunparse=1.6.3
  - async-timeout=3.0.1
  - attrs=21.2.0
  - beautifulsoup4=4.10.0
  - blas=1.0
  - blinker=1.4
  - blosc=1.21.0
  - bokeh=2.3.3
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.17.2
  - c-blosc2=2.0.4
  - ca-certificates=2021.10.8
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=4.2.4
  - cairo=1.16.0
  - certifi=2021.10.8
  - cffi=1.14.6
  - cfitsio=3.470
  - chardet=4.0.0
  - charls=2.2.0
  - click=8.0.3
  - cloudpickle=2.0.0
  - colorama=0.4.4
  - cryptography=3.4.8
  - cudatoolkit=11.1.1
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask=2021.9.1
  - dask-core=2021.9.1
  - dataclasses=0.8
  - dbus=1.13.6
  - decorator=4.4.2
  - distributed=2021.9.1
  - drms=0.6.2
  - expat=2.4.1
  - ffmpeg=4.4.0
  - fontconfig=2.13.1
  - freetype=2.10.4
  - fsspec=2021.10.1
  - gast=0.4.0
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.68.4
  - glib-tools=2.68.4
  - glymur=0.9.4
  - gmp=6.2.1
  - gnutls=3.6.13
  - google-auth=1.35.0
  - google-auth-oauthlib=0.4.6
  - google-pasta=0.2.0
  - graphite2=1.3.13
  - greenlet=1.1.2
  - grpc-cpp=1.37.1
  - grpcio=1.37.1
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - h5netcdf=0.11.0
  - h5py=3.1.0
  - harfbuzz=2.9.1
  - hdf5=1.10.6
  - heapdict=1.0.1
  - icu=68.1
  - idna=2.10
  - imagecodecs=2021.8.26
  - imageio=2.9.0
  - importlib-metadata=4.8.1
  - intel-openmp=2021.3.0
  - isodate=0.6.0
  - jasper=1.900.1
  - jbig=2.1
  - jinja2=3.0.2
  - joblib=1.1.0
  - jpeg=9d
  - jplephem=2.15
  - jxrlib=1.1
  - keras=2.6.0
  - keras-preprocessing=1.1.2
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libaec=1.0.6
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=11.1.0
  - libcurl=7.79.1
  - libdeflate=1.8
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.68.4
  - libgomp=11.2.0
  - libiconv=1.16
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm11=11.1.0
  - libnghttp2=1.43.0
  - libogg=1.3.4
  - libopenblas=0.3.18
  - libopencv=4.5.2
  - libopus=1.3.1
  - libpng=1.6.37
  - libpq=13.3
  - libprotobuf=3.15.8
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.3.0
  - libuuid=2.32.1
  - libuv=1.42.0
  - libvorbis=1.3.7
  - libwebp-base=1.2.1
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.12
  - libxslt=1.1.33
  - libzlib=1.2.11
  - libzopfli=1.0.3
  - locket=0.2.0
  - lxml=4.6.3
  - lz4-c=1.9.3
  - markdown=3.3.4
  - markupsafe=2.0.1
  - matplotlib-base=3.4.3
  - mkl=2021.3.0
  - msgpack-python=1.0.2
  - multidict=5.2.0
  - mysql-common=8.0.25
  - mysql-libs=8.0.25
  - ncurses=6.2
  - nettle=3.6
  - networkx=2.6.3
  - ninja=1.10.2
  - nspr=4.30
  - nss=3.69
  - numpy=1.19.5
  - oauthlib=3.1.1
  - olefile=0.46
  - opencv=4.5.2
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - opt_einsum=3.3.0
  - packaging=21.0
  - pandas=1.3.3
  - parfive=1.5.0
  - partd=1.2.0
  - pcre=8.45
  - pillow=8.3.2
  - pip=21.3
  - pixman=0.40.0
  - platformdirs=2.3.0
  - pooch=1.5.2
  - protobuf=3.15.8
  - psutil=5.8.0
  - pthread-stubs=0.4
  - py-opencv=4.5.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pyerfa=2.0.0
  - pyjwt=2.2.0
  - pyopenssl=21.0.0
  - pyparsing=2.4.7
  - pysocks=1.7.1
  - python=3.9.7
  - python-dateutil=2.8.2
  - python-flatbuffers=1.12
  - python_abi=3.9
  - pytorch=1.9.1
  - pytz=2021.3
  - pyu2f=0.1.5
  - pywavelets=1.1.1
  - pyyaml=5.4.1
  - qt=5.12.9
  - re2=2021.08.01
  - readline=8.1
  - reproject=0.8
  - requests=2.25.1
  - requests-file=1.5.1
  - requests-oauthlib=1.3.0
  - requests-toolbelt=0.9.1
  - rsa=4.7.2
  - scikit-image=0.18.3
  - scikit-learn=1.0
  - scipy=1.7.1
  - setuptools=58.2.0
  - six=1.15.0
  - snappy=1.1.8
  - sortedcontainers=2.4.0
  - soupsieve=2.0.1
  - sqlalchemy=1.4.25
  - sqlite=3.36.0
  - sunpy=3.0.2
  - tblib=1.7.0
  - tensorboard=2.6.0
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.8.0
  - tensorflow=2.6.0
  - tensorflow-base=2.6.0
  - tensorflow-estimator=2.6.0
  - termcolor=1.1.0
  - threadpoolctl=3.0.0
  - tifffile=2021.10.12
  - tk=8.6.11
  - toolz=0.11.1
  - torchaudio=0.9.1
  - torchvision=0.2.2
  - tornado=6.1
  - tqdm=4.62.3
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - tzdata=2021c
  - urllib3=1.26.7
  - werkzeug=2.0.1
  - wheel=0.37.0
  - wrapt=1.12.1
  - x264=1!161.3030
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.7.0
  - zeep=4.1.0
  - zfp=0.5.5
  - zict=2.0.0
  - zipp=3.6.0
  - zlib=1.2.11
  - zstd=1.5.0
